name: Auto Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  Windows:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        product: [Client]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
            path: ${{ matrix.product }}
      - run: |
            ls -l
            cd Client/dist
            ls -l
          
#   macOS:
#     runs-on: macos-10.15
#     strategy:
#       matrix:
#         product: [Client, Console]
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.release_tag }}!"
