name: Auto Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  Windows:
    runs-on: windows-2016
    strategy:
      matrix:
        product: [Client, Console]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: github.event.inputs.release_tag
      - run: |
          function current_branch () {
            local folder="$(pwd)"
            [ -n "$1" ] && folder="$1"
            git -C "$folder" rev-parse --abbrev-ref HEAD | grep -v HEAD || \
            git -C "$folder" describe --exact-match HEAD || \
            git -C "$folder" rev-parse HEAD
          }
          current_branch .
          
#   macOS:
#     runs-on: macos-10.15
#     strategy:
#       matrix:
#         product: [Client, Console]
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.release_tag }}!"
