name: Auto Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  Windows:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        product: [Client]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ${{ matrix.product }}
      - uses: papeloto/action-zip@v1
        with:
          files: ${{ matrix.product }}/dist/windows/
          recursive: false
          dest: pro.zip #PYCM-${{ matrix.product }}-${{ github.event.inputs.release_tag }}-Windows.zip
      - uses: actions/upload-artifact@v2
        with:
          name: win-${{ matrix.product }}
          path: pro.zip
#   macOS:
#     runs-on: macos-10.15
#     strategy:
#       matrix:
#         product: [Client, Console]
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.release_tag }}!"
