name: Auto Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  Windows:
    runs-on: windows-2016
    strategy:
      matrix:
        product: [Client]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Init
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build
        run: |
          cd ${{ matrix.product }}
          pyinstaller --clean -D -i UI/Resources/logo.ico --hidden-import=PyQt5.sip Main.py
      - run: |
          ls
          cd Client
          ls
          cd dist
          ls
      # - uses: papeloto/action-zip@v1
      #   with:
      #     files: dist/
      #     recursive: false
      #     dest: pro.zip #PYCM-${{ matrix.product }}-${{ github.event.inputs.release_tag }}-Windows.zip
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: win-${{ matrix.product }}
      #     path: pro.zip
#   macOS:
#     runs-on: macos-10.15
#     strategy:
#       matrix:
#         product: [Client, Console]
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.release_tag }}!"
