name: Auto Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #[windows-2016]
        product: [Client]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          
#   macOS:
#     runs-on: macos-10.15
#     strategy:
#       matrix:
#         product: [Client, Console]
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.release_tag }}!"
