name: PYCM-Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        program: [Console]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Display current Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Pre build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build Console
        if: ${{ matrix.program == 'Console' }}
        run: |
          cd ${{ matrix.program }}
          pyinstaller Main.py -p LoadConfig.py -p NetworkDiscover.py -p Packages.py -p PrivateMessage.py -p Resources_rc.py -p Threadings.py -p UI/Dashboard.py -p UI/DashboardUI.py -p UI/Login.py -p UI/LoginUI.py -F -w -i UI/Resources/logo.ico --clean -y
      
      - name: Zip binary for Mac and Linux
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cp -R ${{ matrix.program }}/dist/Main ./Builded
          zip -r Builded.zip Builded
          ls
      
      - name: Zip binary for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          xcopy .\${{ matrix.program }}\dist\Main .\Builded /s /e /y
          zip -r Builded.zip Builded
          ls
 
