name: Build-Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Console:
    runs-on: windows-2016
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Console
        run: |
          "BUILD_INFO = 'Windows v"+${{ steps.tag.outputs.result }}+" (MSVC, 64-bit)'" | Out-File -FilePath BuildInfo.py -Encoding UTF8
      - name: Build
        working-directory: Console
        run: |
          nuitka --standalone --msvc=14.0 --lto=yes --windows-icon-from-ico=Resources/Logo.ico `
                 --windows-company-name=HCC --windows-uac-admin --windows-disable-console `
                 --windows-product-name=PYCM-Console --windows-product-version=${{ steps.tag.outputs.result }} `
                 --windows-file-description=PYCM-Console --windows-file-version=${{ steps.tag.outputs.result }} `
                 --include-data-file=Alibaba-PuHuiTi-Regular.ttf=Alibaba-PuHuiTi-Regular.ttf `
                 --include-data-file=Alibaba-PuHuiTi-Bold.ttf=Alibaba-PuHuiTi-Bold.ttf `
                 --include-data-file=Translation/*.qm=Translation/ `
                 --plugin-enable=qt-plugins --assume-yes-for-downloads `
                 --output-dir=Build ConsoleMain.py
      - name: Check build
        working-directory: Console
        run: if(!(Test-Path Build/ConsoleMain.dist/ConsoleMain.exe)){ exit 1 }
      - name: Zip files
        uses: papeloto/action-zip@v1
        with:
          files: Console/Build/ConsoleMain.dist/
          dest: PYCM-Console-Windows.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Console-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-Client:
    runs-on: windows-2016
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Add build info
        working-directory: Client
        env:
          RELEASE_TAG: ${{ steps.tag.outputs.result }}
        run: |
          "BUILD_INFO = 'Windows v"+${{ steps.tag.outputs.result }}+" (MSVC, 64-bit)'" | Out-File -FilePath BuildInfo.py -Encoding UTF8
      - name: Build
        working-directory: Client
        run: |
          nuitka --standalone --msvc=14.0 --lto=yes --windows-icon-from-ico=Resources/Logo.ico `
                 --windows-company-name=HCC --windows-uac-admin --windows-disable-console `
                 --windows-product-name=PYCM-Client --windows-product-version=${{ steps.tag.outputs.result }} `
                 --windows-file-description=PYCM-Client --windows-file-version=${{ steps.tag.outputs.result }} `
                 --include-data-file=Alibaba-PuHuiTi-Regular.ttf=Alibaba-PuHuiTi-Regular.ttf `
                 --include-data-file=Alibaba-PuHuiTi-Bold.ttf=Alibaba-PuHuiTi-Bold.ttf `
                 --include-data-file=Translation/*.qm=Translation/ `
                 --plugin-enable=qt-plugins --assume-yes-for-downloads `
                 --output-dir=Build ClientMain.py
      - name: Check build
        working-directory: Client
        run: if(!(Test-Path Build/ClientMain.dist/ClientMain.exe)){ exit 1 }
      - name: Zip files
        uses: papeloto/action-zip@v1
        with:
          files: Client/Build/ClientMain.dist/
          dest: PYCM-Client-Windows.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Client-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}