name: Build Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Console:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
      - name: Build
        working-directory: Console
        run: |
          set version=%GITHUB_REF:*tags/v=%
          nuitka --standalone --msvc=14.0 --windows-icon-from-ico=Resources/Logo.ico `
                 --windows-company-name=HCC --windows-uac-admin --windows-disable-console `
                 --windows-product-name=PYCM-Console --windows-product-version=%version% `
                 --windows-file-description=PYCM-Console --windows-file-version=%version% `
                 --plugin-enable=qt-plugins --assume-yes-for-downloads `
                 --output-dir=Build Main.py
      - name: Copy FFMpeg
        working-directory: Console
        run: |
          mkdir Build/Main.dist/Utils
          cp Utils/ffmpeg-win.exe Build/Main.dist/Utils/ffmpeg-win.exe
      - name: Zip files
        uses: papeloto/action-zip@v1
        with:
          files: Console/Build/Main.dist/
          dest: PYCM-Console-${{ runner.os }}.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Console-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}