name: Build Mac

on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Console:
    runs-on: macos-10.15
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install wheel
          pip install -r requirements.txt
          pip install nuitka
      - name: Build
        working-directory: Console
        run: |
          nuitka --standalone \
                 --plugin-enable=qt-plugins --assume-yes-for-downloads \
                 --output-dir=Build Main.py
      - name: Copy FFMpeg
        working-directory: Console
        run: |
          mkdir Build/Main.dist/Utils
          cp Utils/ffmpeg-mac Build/Main.dist/Utils/ffmpeg-mac
      - name: Zip files
        uses: papeloto/action-zip@v1
        with:
          files: Console/Build/Main.dist/
          dest: PYCM-Console-${{ runner.os }}.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: PYCM-Console-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}